/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import clases.GTotalRecaudado;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.LocalTime;

/**
 *
 * @author amc77
 */
public class FTotalRecaudado extends javax.swing.JFrame {

    /**
     * Creates new form FTotalRecaudado
     */
    public FTotalRecaudado() {
        initComponents();
        
        
           this.setLocationRelativeTo(null);
        
        FECHA.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        HORA.setText(LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss")));
        AÑO.setText(String.valueOf(LocalDate.now().getYear()));

        
        GTotalRecaudado objetotrabajo = new GTotalRecaudado();
         objetotrabajo.mostrarTotalRecaudado(TABLATOTAL,TotalRecaudadoF);


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FECHA = new javax.swing.JTextField();
        HORA = new javax.swing.JTextField();
        AÑO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLATOTAL = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TotalRecaudadoF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FECHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FECHAActionPerformed(evt);
            }
        });
        jPanel1.add(FECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, -1));

        HORA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HORAActionPerformed(evt);
            }
        });
        jPanel1.add(HORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 100, -1));

        AÑO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AÑOActionPerformed(evt);
            }
        });
        jPanel1.add(AÑO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("FECHA DE REPORTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setText("HORA DE REPORTE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("AÑO DE REPORTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 110));

        TABLATOTAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLATOTAL.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TABLATOTAL);
        TABLATOTAL.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 740, 320));

        jLabel4.setText("TOTAL RECAUDADO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        TotalRecaudadoF.setText("00,00");
        TotalRecaudadoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalRecaudadoFActionPerformed(evt);
            }
        });
        jPanel1.add(TotalRecaudadoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FECHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FECHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FECHAActionPerformed

    private void TotalRecaudadoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalRecaudadoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalRecaudadoFActionPerformed

    private void HORAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HORAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HORAActionPerformed

    private void AÑOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AÑOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AÑOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTotalRecaudado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTotalRecaudado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTotalRecaudado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTotalRecaudado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTotalRecaudado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AÑO;
    private javax.swing.JTextField FECHA;
    private javax.swing.JTextField HORA;
    private javax.swing.JTable TABLATOTAL;
    private javax.swing.JTextField TotalRecaudadoF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
