
package interfaz;
import proyectotienda.Salados;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.concurrent.ForkJoinTask;
import javax.accessibility.AccessibleAction;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectotienda.Dulce;

public class JFrameTienda extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTienda
     */
    @Override
public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("Fondo/icon.png"));


   return retValue;
}
    DefaultTableModel modelo;
    public JFrameTienda() {
        initComponents();
        
        modelo=(DefaultTableModel)ProductosCargados.getModel();
        BtnVerProducto.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        SaladoDulce = new javax.swing.JComboBox<>();
        TxtOpcionesSaladoDulce = new javax.swing.JLabel();
        BtnVerProducto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductosCargados = new javax.swing.JTable();
        TxtOpcionesSaladoDulce1 = new javax.swing.JLabel();
        TxtOpcionesSaladoDulce2 = new javax.swing.JLabel();
        TxtOpcionesSaladoDulce3 = new javax.swing.JLabel();
        TipoSalado = new javax.swing.JComboBox<>();
        TipoDulce = new javax.swing.JComboBox<>();
        BtnCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO TIENDA DIGITAL\n");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(905, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TIENDA DIGITAL DON CHUNCHULIN");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(126, 23, 624, 41);

        SaladoDulce.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        SaladoDulce.setForeground(new java.awt.Color(255, 255, 255));
        SaladoDulce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRODUCTOS SALADOS", "PRODUCTOS DULCES" }));
        SaladoDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaladoDulceActionPerformed(evt);
            }
        });
        getContentPane().add(SaladoDulce);
        SaladoDulce.setBounds(504, 131, 223, 26);

        TxtOpcionesSaladoDulce.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtOpcionesSaladoDulce.setForeground(new java.awt.Color(0, 0, 0));
        TxtOpcionesSaladoDulce.setText("ELIGE LA CATEGORIA DE PRODUCTOS QUE QUIERES VER:");
        getContentPane().add(TxtOpcionesSaladoDulce);
        TxtOpcionesSaladoDulce.setBounds(34, 134, 398, 19);

        BtnVerProducto.setForeground(new java.awt.Color(0, 0, 0));
        BtnVerProducto.setText("ACEPTAR");
        BtnVerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerProductoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVerProducto);
        BtnVerProducto.setBounds(759, 132, 90, 24);

        ProductosCargados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MARCA", "PRODUCTO", "CANTIDAD DISP.", "PRECIO", "SABOR DISP."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductosCargados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ProductosCargados.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ProductosCargados.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(ProductosCargados);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(34, 184, 815, 135);

        TxtOpcionesSaladoDulce1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtOpcionesSaladoDulce1.setForeground(new java.awt.Color(0, 0, 0));
        TxtOpcionesSaladoDulce1.setText("ELIGE EL PRODUCTO QUE QUIERES COMPRAR Y CUÁNTOS:");
        getContentPane().add(TxtOpcionesSaladoDulce1);
        TxtOpcionesSaladoDulce1.setBounds(34, 346, 410, 19);

        TxtOpcionesSaladoDulce2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtOpcionesSaladoDulce2.setForeground(new java.awt.Color(0, 0, 0));
        TxtOpcionesSaladoDulce2.setText("PRODUCTOS SALADOS:");
        getContentPane().add(TxtOpcionesSaladoDulce2);
        TxtOpcionesSaladoDulce2.setBounds(529, 398, 161, 19);

        TxtOpcionesSaladoDulce3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtOpcionesSaladoDulce3.setForeground(new java.awt.Color(0, 0, 0));
        TxtOpcionesSaladoDulce3.setText("PRODUCTOS DULCES:");
        getContentPane().add(TxtOpcionesSaladoDulce3);
        TxtOpcionesSaladoDulce3.setBounds(34, 398, 152, 19);

        TipoSalado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TipoSalado.setForeground(new java.awt.Color(255, 255, 255));
        TipoSalado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIZZA", "BIZCOCHO", "PAPAS FRITAS", "MORTADELA", "EMPANADA", " " }));
        TipoSalado.setSelectedIndex(5);
        TipoSalado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoSaladoActionPerformed(evt);
            }
        });
        getContentPane().add(TipoSalado);
        TipoSalado.setBounds(737, 395, 113, 26);

        TipoDulce.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        TipoDulce.setForeground(new java.awt.Color(255, 255, 255));
        TipoDulce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHUPETE SABOR PIÑA", "CHUPETE SABOR MANDARINA", "CHUPETE SABOR SANDIA", "CHUPETE SABOR MANZANA", "CHUPETE SABOR COCO", "" }));
        TipoDulce.setSelectedIndex(5);
        TipoDulce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDulceActionPerformed(evt);
            }
        });
        getContentPane().add(TipoDulce);
        TipoDulce.setBounds(233, 395, 199, 26);

        BtnCompra.setForeground(new java.awt.Color(0, 0, 0));
        BtnCompra.setText("COMPRAR");
        BtnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompraActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCompra);
        BtnCompra.setBounds(415, 459, 90, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/itl.cat_hexagon-wallpaper_3089727.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 890, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaladoDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaladoDulceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaladoDulceActionPerformed

    private void BtnVerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerProductoActionPerformed
        Salados Sds= new Salados();
     
        Dulce Dcs= new Dulce();
        if (SaladoDulce.getSelectedIndex()==0) {
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaboroTipo()});
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaborotipo2()});
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaborotipo3()});
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaborotipo4()});
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaborotipo5()});
            modelo.addRow(new Object[]{Sds.getMarca(), Sds.getNombre(), Sds.getCantidadStock(), Sds.getPrecio(), Sds.getSaborotipo6()});
            
        } 
        else {
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor()});
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor2()});
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor3()});
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor3()});
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor4()});
            modelo.addRow(new Object[]{Dcs.getMarca(), Dcs.getNombre(), Dcs.getCantidadStock(), Dcs.getPrecio(), Dcs.getSabor5()});
             
        
        }
    }//GEN-LAST:event_BtnVerProductoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setBackground(Color.yellow);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void TipoDulceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDulceActionPerformed
        
       
                                                  
    }//GEN-LAST:event_TipoDulceActionPerformed

    public double SumarPrecios (){
        Dulce Precio= new Dulce();
        Salados Precio2= new Salados();
        double a= Precio.getPrecio();
        double b= Precio2.getPrecio();
        double resul = a + b;

        return resul;
        
    }
    private void BtnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompraActionPerformed
        Dulce TipoProducto= new Dulce();
        Salados TipoProducto2= new Salados();
        if (TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==5) 
{
            JOptionPane.showMessageDialog(BtnCompra, "No ha seleccionado un producto para comprar");         
        }
        else{
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==1)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==1 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==1 && TipoSalado.getSelectedIndex()==1)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==2 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
           if (TipoDulce.getSelectedIndex()==0 && TipoSalado.getSelectedIndex()==5)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
               
           if(TipoDulce.getSelectedIndex()==5 && TipoSalado.getSelectedIndex()==0)
               
                JOptionPane.showMessageDialog(BtnCompra, "El precio total es: " +SumarPrecios());
        else
        {
       
        JOptionPane.showMessageDialog(rootPane, "¡Se registró exitosamente!");
        }
                   
    }//GEN-LAST:event_BtnCompraActionPerformed

        }
    private void TipoSaladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoSaladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoSaladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCompra;
    private javax.swing.JButton BtnVerProducto;
    private javax.swing.JTable ProductosCargados;
    private javax.swing.JComboBox<String> SaladoDulce;
    private javax.swing.JComboBox<String> TipoDulce;
    private javax.swing.JComboBox<String> TipoSalado;
    private javax.swing.JLabel TxtOpcionesSaladoDulce;
    private javax.swing.JLabel TxtOpcionesSaladoDulce1;
    private javax.swing.JLabel TxtOpcionesSaladoDulce2;
    private javax.swing.JLabel TxtOpcionesSaladoDulce3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
